"""Initial database schema.

Revision ID: ff74e4d598f6
Revises:
Create Date: 2024-06-21 00:14:49.510947

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ff74e4d598f6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "youtube_chat_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("message_text", sa.String(), nullable=False),
        sa.Column("author_name", sa.String(), nullable=False),
        sa.Column("author_image_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("youtube_chat_messages")
    # ### end Alembic commands ###
