"""Add created_at column to youtube_chat_messages

Revision ID: 935a522dc2e9
Revises: ff74e4d598f6
Create Date: 2024-06-21 00:52:21.916911

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "935a522dc2e9"
down_revision = "ff74e4d598f6"
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("youtube_chat_messages", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_chat_messages", "created_at")
    # ### end Alembic commands ###
